#%RAML 1.0 Trait
  headers:
    client_id:
      description: The Client-ID of the Application. Will be provided by the Portal
      type: string
      example: cvfbgsn_009nhkaakds
      required: true
    client_secret:
      description: The Client-Secret of Application. Will be provided by the Portal.
      type: string
      example: 009_retsvalnsdj7jadfy74
      required: true