#%RAML 1.0 Trait
  headers:
    Content-Type:
      description: HTTP-Standard Parameter. Header Field  RFC 7231. Media Types  RFC 2046.
      type: string
      required: true
      default: application/json; charset=utf-8
      example: 'Content-Type: application/json; charset=utf-8'